replicaCount: 1
image:
  repository: ajay048/go-web-app
  pullPolicy: IfNotPresent
  tag: "12332133913"
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific